columns:
  age: int
  sex: category
  bmi: float
  children: int
  smoker: category
  region: category
  expenses: float

# for data validatiom
numerical_columns:
  - age 
  - bmi
  - children
  - expenses
categorical_columns:
  - sex
  - smoker
  - region